INSERT IGNORE INTO `set_countries` (`id`, `name`, `alpha2code`, `alpha3code`) VALUES
(4, 'Afghanistan', 'AF', 'AFG'),
(8, 'Albania', 'AL', 'ALB'),
(10, 'Antarctica', 'AQ', 'ATA'),
(12, 'Algeria', 'DZ', 'DZA'),
(16, 'American Samoa', 'AS', 'ASM'),
(20, 'Andorra', 'AD', 'AND'),
(24, 'Angola', 'AO', 'AGO'),
(28, 'Antigua and Barbuda', 'AG', 'ATG'),
(31, 'Azerbaijan', 'AZ', 'AZE'),
(32, 'Argentina', 'AR', 'ARG'),
(36, 'Australia', 'AU', 'AUS'),
(40, 'Austria', 'AT', 'AUT'),
(44, 'Bahamas', 'BS', 'BHS'),
(48, 'Bahrain', 'BH', 'BHR'),
(50, 'Bangladesh', 'BD', 'BGD'),
(51, 'Armenia', 'AM', 'ARM'),
(52, 'Barbados', 'BB', 'BRB'),
(56, 'Belgium', 'BE', 'BEL'),
(60, 'Bermuda', 'BM', 'BMU'),
(64, 'Bhutan', 'BT', 'BTN'),
(68, 'Bolivia', 'BO', 'BOL'),
(70, 'Bosnia-Herzegovina', 'BA', 'BIH'),
(72, 'Botswana', 'BW', 'BWA'),
(74, 'Bouvet island', 'BV', 'BVT'),
(76, 'Brazil', 'BR', 'BRA'),
(84, 'Belize', 'BZ', 'BLZ'),
(86, 'British Indian Ocean Territory', 'IO', 'IOT'),
(90, 'Solomon Islands', 'SB', 'SLB'),
(92, 'British Virgin Islands', 'VG', 'VGB'),
(96, 'Brunei Darussalam', 'BN', 'BRN'),
(100, 'Bulgaria', 'BG', 'BGR'),
(104, 'Myanmar', 'MM', 'MMR'),
(108, 'Burundi', 'BI', 'BDI'),
(112, 'Belarus', 'BY', 'BLR'),
(116, 'Cambodia', 'KH', 'KHM'),
(120, 'Cameroon', 'CM', 'CMR'),
(124, 'Canada', 'CA', 'CAN'),
(132, 'Cape Verde Islands', 'CV', 'CPV'),
(136, 'Cayman Islands', 'KY', 'CYM'),
(140, 'Central African Republic', 'CF', 'CAF'),
(144, 'Sri Lanka', 'LK', 'LKA'),
(148, 'Chad', 'TD', 'TCD'),
(152, 'Chile', 'CL', 'CHL'),
(156, 'China PR', 'CN', 'CHN'),
(158, 'Taiwan, province of china', 'TW', 'TWN'),
(162, 'Christmas island', 'CX', 'CXR'),
(166, 'Cocos (keeling) islands', 'CC', 'CCK'),
(170, 'Colombia', 'CO', 'COL'),
(174, 'Comoros', 'KM', 'COM'),
(175, 'Mayotte', 'YT', 'MYT'),
(178, 'Congo', 'CG', 'COG'),
(180, 'Congo DR', 'CD', 'COD'),
(184, 'Cook Islands', 'CK', 'COK'),
(188, 'Costa Rica', 'CR', 'CRI'),
(191, 'Croatia', 'HR', 'HRV'),
(192, 'Cuba', 'CU', 'CUB'),
(196, 'Cyprus', 'CY', 'CYP'),
(203, 'Czech Republic', 'CZ', 'CZE'),
(204, 'Benin', 'BJ', 'BEN'),
(208, 'Denmark', 'DK', 'DNK'),
(212, 'Dominica', 'DM', 'DMA'),
(214, 'Dominican Republic', 'DO', 'DOM'),
(218, 'Ecuador', 'EC', 'ECU'),
(222, 'El Salvador', 'SV', 'SLV'),
(226, 'Equatorial Guinea', 'GQ', 'GNQ'),
(231, 'Ethiopia', 'ET', 'ETH'),
(232, 'Eritrea', 'ER', 'ERI'),
(233, 'Estonia', 'EE', 'EST'),
(234, 'Faroe Islands', 'FO', 'FRO'),
(238, 'Falkland islands (malvinas)', 'FK', 'FLK'),
(239, 'South Georgia and the South Sandwich islands', 'GS', 'SGS'),
(242, 'Fiji', 'FJ', 'FJI'),
(246, 'Finland', 'FI', 'FIN'),
(249, 'France, metropolitan', 'FX', 'XFX'),
(250, 'France', 'FR', 'FRA'),
(254, 'French Guiana', 'GF', 'GUF'),
(258, 'French Polynesia', 'PF', 'PYF'),
(260, 'French Southern Territories', 'TF', 'ATF'),
(262, 'Djibouti', 'DJ', 'DJI'),
(266, 'Gabon', 'GA', 'GAB'),
(268, 'Georgia', 'GE', 'GEO'),
(270, 'Gambia', 'GM', 'GMB'),
(275, 'Palestine', 'PS', 'PSE'),
(276, 'Germany', 'DE', 'DEU'),
(288, 'Ghana', 'GH', 'GHA'),
(292, 'Gibraltar', 'GI', 'GIB'),
(296, 'Kiribati', 'KI', 'KIR'),
(300, 'Greece', 'GR', 'GRC'),
(304, 'Greenland', 'GL', 'GRL'),
(308, 'Grenada', 'GD', 'GRD'),
(312, 'Guadeloupe', 'GP', 'GLP'),
(316, 'Guam', 'GU', 'GUM'),
(320, 'Guatemala', 'GT', 'GTM'),
(324, 'Guinea', 'GN', 'GIN'),
(328, 'Guyana', 'GY', 'GUY'),
(332, 'Haiti', 'HT', 'HTI'),
(336, 'Holy See (Vatican City state)', 'VA', 'VAT'),
(340, 'Honduras', 'HN', 'HND'),
(344, 'Hong Kong', 'HK', 'HKG'),
(348, 'Hungary', 'HU', 'HUN'),
(352, 'Iceland', 'IS', 'ISL'),
(356, 'India', 'IN', 'IND'),
(360, 'Indonesia', 'ID', 'IDN'),
(364, 'Iran', 'IR', 'IRN'),
(368, 'Iraq', 'IQ', 'IRQ'),
(372, 'Ireland Republic', 'IE', 'IRL'),
(376, 'Israel', 'IL', 'ISR'),
(380, 'Italy', 'IT', 'ITA'),
(384, 'Côte d\'Ivoire', 'CI', 'CIV'),
(388, 'Jamaica', 'JM', 'JAM'),
(392, 'Japan', 'JP', 'JPN'),
(398, 'Kazakhstan', 'KZ', 'KAZ'),
(400, 'Jordan', 'JO', 'JOR'),
(404, 'Kenya', 'KE', 'KEN'),
(408, 'Korea DPR', 'KP', 'PRK'),
(410, 'Korea Republic', 'KR', 'KOR'),
(414, 'Kuwait', 'KW', 'KWT'),
(417, 'Kyrgyzstan', 'KG', 'KGZ'),
(418, 'Laos', 'LA', 'LAO'),
(422, 'Lebanon', 'LB', 'LBN'),
(426, 'Lesotho', 'LS', 'LSO'),
(428, 'Latvia', 'LV', 'LVA'),
(430, 'Liberia', 'LR', 'LBR'),
(434, 'Libya', 'LY', 'LBY'),
(438, 'Liechtenstein', 'LI', 'LIE'),
(440, 'Lithuania', 'LT', 'LTU'),
(442, 'Luxembourg', 'LU', 'LUX'),
(446, 'Macao', 'MO', 'MAC'),
(450, 'Madagascar', 'MG', 'MDG'),
(454, 'Malawi', 'MW', 'MWI'),
(458, 'Malaysia', 'MY', 'MYS'),
(462, 'Maldives', 'MV', 'MDV'),
(466, 'Mali', 'ML', 'MLI'),
(470, 'Malta', 'MT', 'MLT'),
(474, 'Martinique', 'MQ', 'MTQ'),
(478, 'Mauritania', 'MR', 'MRT'),
(480, 'Mauritius', 'MU', 'MUS'),
(484, 'Mexico', 'MX', 'MEX'),
(492, 'Monaco', 'MC', 'MCO'),
(496, 'Mongolia', 'MN', 'MNG'),
(498, 'Moldova', 'MH', 'MHL'),
(499, 'Montenegro', 'ME', 'MNE'),
(500, 'Montserrat', 'MS', 'MSR'),
(504, 'Morocco', 'MA', 'MAR'),
(508, 'Mozambique', 'MZ', 'MOZ'),
(512, 'Oman', 'OM', 'OMN'),
(516, 'Namibia', 'NA', 'NAM'),
(520, 'Nauru', 'NR', 'NRU'),
(524, 'Nepal', 'NP', 'NPL'),
(528, 'Netherlands', 'NL', 'NLD'),
(530, 'Netherlands antilles', 'AN', 'XAN'),
(531, 'Curaçao', 'CW', 'CUW'),
(533, 'Aruba', 'AW', 'ABW'),
(534, 'Sint Maarten', 'SX', 'SXM'),
(535, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES'),
(540, 'New Caledonia', 'NC', 'NCL'),
(548, 'Vanuatu', 'VU', 'VUT'),
(554, 'New Zealand', 'NZ', 'NZL'),
(558, 'Nicaragua', 'NI', 'NIC'),
(562, 'Niger', 'NE', 'NER'),
(566, 'Nigeria', 'NG', 'NGA'),
(570, 'Niue', 'NU', 'NIU'),
(574, 'Norfolk island', 'NF', 'NFK'),
(578, 'Norway', 'NO', 'NOR'),
(580, 'Northern Mariana Islands', 'MP', 'MNP'),
(581, 'United states minor outlying islands', 'UM', 'UMI'),
(583, 'Micronesia, federated states of', 'FM', 'FSM'),
(584, 'Marshall islands', 'MD', 'MDA'),
(585, 'Palau', 'PW', 'PLW'),
(586, 'Pakistan', 'PK', 'PAK'),
(591, 'Panama', 'PA', 'PAN'),
(598, 'Papua New Guinea', 'PG', 'PNG'),
(600, 'Paraguay', 'PY', 'PRY'),
(604, 'Peru', 'PE', 'PER'),
(608, 'Philippines', 'PH', 'PHL'),
(612, 'Pitcairn', 'PN', 'PCN'),
(616, 'Poland', 'PL', 'POL'),
(620, 'Portugal', 'PT', 'PRT'),
(624, 'Guinea-Bissau', 'GW', 'GNB'),
(626, 'East Timor', 'LS', 'XLS'),
(630, 'Puerto Rico', 'PR', 'PRI'),
(634, 'Qatar', 'QA', 'QAT'),
(638, 'Reunion', 'RE', 'REU'),
(642, 'Romania', 'RO', 'ROU'),
(643, 'Russia', 'RU', 'RUS'),
(646, 'Rwanda', 'RW', 'RWA'),
(654, 'St. helena', 'SH', 'SHN'),
(659, 'St. Kitts and Nevis', 'KN', 'KNA'),
(660, 'Anguilla', 'AI', 'AIA'),
(662, 'St. Lucia', 'LC', 'LCA'),
(663, 'Saint Martin', 'MF', 'MAF'),
(666, 'St. pierre and miquelon', 'PM', 'SPM'),
(670, 'St. Vincent and the Grenadines', 'VC', 'VCT'),
(674, 'San Marino', 'SM', 'SMR'),
(678, 'São Tomé e Príncipe', 'ST', 'STP'),
(682, 'Saudi Arabia', 'SA', 'SAU'),
(686, 'Senegal', 'SN', 'SEN'),
(688, 'Serbia', 'RS', 'SRB'),
(690, 'Seychelles', 'SC', 'SYC'),
(694, 'Sierra Leone', 'SL', 'SLE'),
(702, 'Singapore', 'SG', 'SGP'),
(703, 'Slovakia', 'SK', 'SVK'),
(704, 'Vietnam', 'VN', 'VNM'),
(705, 'Slovenia', 'SI', 'SVN'),
(706, 'Somalia', 'SO', 'SOM'),
(710, 'South Africa', 'ZA', 'ZAF'),
(716, 'Zimbabwe', 'ZW', 'ZWE'),
(724, 'Spain', 'ES', 'ESP'),
(728, 'South Sudan', 'SS', 'SSD'),
(729, 'Sudan', 'SD', 'SDN'),
(732, 'Western Sahara', 'EH', 'ESH'),
(740, 'Suriname', 'SR', 'SUR'),
(744, 'Svalbard and Jan Mayen islands', 'SJ', 'SJM'),
(748, 'Swaziland', 'SZ', 'SWZ'),
(752, 'Sweden', 'SE', 'SWE'),
(756, 'Switzerland', 'CH', 'CHE'),
(760, 'Syria', 'SY', 'SYR'),
(762, 'Tajikistan', 'TJ', 'TJK'),
(764, 'Thailand', 'TH', 'THA'),
(768, 'Togo', 'TG', 'TGO'),
(772, 'Tokelau', 'TK', 'TKL'),
(776, 'Tonga', 'TO', 'TON'),
(780, 'Trinidad and Tobago', 'TT', 'TTO'),
(784, 'United Arab Emirates', 'AE', 'ARE'),
(788, 'Tunisia', 'TN', 'TUN'),
(792, 'Turkey', 'TR', 'TUR'),
(795, 'Turkmenistan', 'TM', 'TKM'),
(796, 'Turks and Caicos Islands', 'TC', 'TCA'),
(798, 'Tuvalu', 'TV', 'TUV'),
(800, 'Uganda', 'UG', 'UGA'),
(804, 'Ukraine', 'UA', 'UKR'),
(807, 'Macedonia FYR', 'MK', 'MKD'),
(818, 'Egypt', 'EG', 'EGY'),
(826, 'England', 'EN', 'XEN'),
(831, 'Guernsey', 'GG', 'GGY'),
(832, 'Jersey', 'JE', 'JEY'),
(833, 'Isle of Man', 'IM', 'IMN'),
(834, 'Tanzania', 'TZ', 'TZA'),
(840, 'United States', 'US', 'USA'),
(850, 'US Virgin Islands', 'VI', 'VIR'),
(854, 'Burkina Faso', 'BF', 'BFA'),
(858, 'Uruguay', 'UY', 'URY'),
(860, 'Uzbekistan', 'UZ', 'UZB'),
(862, 'Venezuela', 'VE', 'VEN'),
(876, 'Wallis and Futuna islands', 'WF', 'WLF'),
(882, 'Samoa', 'WS', 'WSM'),
(887, 'Yemen', 'YE', 'YEM'),
(894, 'Zambia', 'ZM', 'ZMB'),
(1002, 'Scotland', 'SC', 'XSC'),
(1012, 'Tahiti', 'TA', 'XTA'),
(1013, 'Wales', 'WA', 'XWA'),
(1014, 'Northern Ireland', 'NI', 'XNI'),
(1015, 'Great Britain', 'GB', 'GBR'),
(1101, 'Asia', 'AS', 'XAS'),
(1102, 'Africa', 'AF', 'XAF'),
(1103, 'N/C America', 'NC', 'XNC'),
(1104, 'South America', 'SA', 'XSA'),
(1105, 'Oceania', 'OC', 'XOC'),
(1106, 'Europe', 'EU', 'XEU'),
(1149, 'Chinese Taipei', 'CT', 'XCT'),
(1312, 'Zanzibar', 'ZA', 'XZA'),
(1328, 'Kosovo', 'KS', 'XKS'),
(1420, 'World', 'WO', 'XWO');