
INSERT IGNORE INTO `set_teams` (`id`, `name`, `officialName`, `city`, `country_id`, `level`, `gender`, `image`) VALUES
(8, 'ADO Den Haag', 'HFC ADO Den Haag', 'Den Haag', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8.png'),
(9, 'Ajax', 'AFC Ajax', 'Amsterdam', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9.png'),
(10, 'AZ', 'Alkmaar Zaanstreek', 'Alkmaar', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10.png'),
(11, 'PSV', 'PSV Eindhoven', 'Eindhoven', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/11.png'),
(12, 'Feyenoord', 'Feyenoord Rotterdam', 'Rotterdam', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12.png'),
(13, 'Heerenveen', 'SC Heerenveen', 'Heerenveen', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/13.png'),
(15, 'Willem II', 'Willem II', 'Tilburg', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15.png'),
(16, 'Twente', 'FC Twente', 'Enschede', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/16.png'),
(17, 'Utrecht', 'FC Utrecht', 'Utrecht', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/17.png'),
(20, 'RKC Waalwijk', 'RKC Waalwijk', 'Waalwijk', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/20.png'),
(21, 'Groningen', 'FC Groningen', 'Groningen', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/21.png'),
(22, 'NEC', 'Nijmegen Eendracht Combinatie', 'Nijmegen', 528, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/152_120x120.png'),
(23, 'PEC Zwolle', 'PEC Zwolle', 'Zwolle', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/23.png'),
(24, 'Vitesse', 'SBV Vitesse', 'Arnhem', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/24.png'),
(29, 'Sparta Rotterdam', 'Sparta Rotterdam', 'Rotterdam', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/29.png'),
(30, 'Heracles', 'Heracles Almelo', 'Almelo', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/30.png'),
(32, 'VVV Venlo', 'VVV Venlo', 'Venlo', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/32.png'),
(33, 'Emmen', 'FC Emmen', 'Emmen', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/33.png'),
(34, 'Go Ahead Eagles', 'Go Ahead Eagles', 'Deventer', 528, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/854_120x120.png'),
(40, 'Cambuur', 'SC Cambuur Leeuwarden', 'Leeuwarden', 528, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/861_120x120.png'),
(44, 'Fortuna Sittard', 'Fortuna Sittard', 'Sittard', 528, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/44.png'),
(674, 'Valencia', 'Valencia CF', 'Valencia', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/674.png'),
(675, 'Real Madrid', 'Real Madrid Club de Fútbol', 'Madrid', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/675.png'),
(676, 'Barcelona', 'FC Barcelona', 'Barcelona', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/676.png'),
(678, 'Athletic Bilbao', 'Athletic Club Bilbao', 'Bilbao', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/678.png'),
(679, 'Atlético Madrid', 'Club Atlético de Madrid', 'Madrid', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/679.png'),
(680, 'Sevilla', 'Sevilla FC', 'Sevilla', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/680.png'),
(681, 'Osasuna', 'CA Osasuna', 'Pamplona (Iruñea)', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/681.png'),
(682, 'Villarreal', 'Villarreal Club de Fútbol', 'Villarreal', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/682.png'),
(683, 'Málaga', 'Málaga Club de Fútbol', 'Malaga', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/683.png'),
(684, 'Real Betis', 'Real Betis Balompié', 'Sevilla', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/684.png'),
(685, 'Albacete', 'Albacete Balompié', 'Albacete', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/685.png'),
(686, 'Mallorca', 'Real Club Deportivo Mallorca', 'Palma de Mallorca', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/686.png'),
(687, 'Real Sociedad', 'Real Sociedad de Fútbol', 'Donostia-San Sebastián', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/687.png'),
(689, 'Real Zaragoza', 'Real Zaragoza', 'Zaragoza', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/689.png'),
(690, 'Real Valladolid', 'Real Valladolid Club de Fútbol', 'Valladolid', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/690.png'),
(691, 'Espanyol', 'Reial Club Deportiu Espanyol', 'Barcelona', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/691.png'),
(692, 'Celta de Vigo', 'Real Club Celta de Vigo', 'Vigo', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/692.png'),
(695, 'Levante', 'Levante UD', 'Valencia', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/695.png'),
(696, 'Deportivo Alavés', 'Deportivo Alavés', 'Vitoria-Gasteiz', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/696.png'),
(697, 'Sporting Gijón', 'Real Sporting de Gijón', 'Gijón', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/697.png'),
(698, 'Getafe', 'Getafe Club de Fútbol', 'Getafe (Madrid)', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/698.png'),
(700, 'Cádiz', 'Cádiz CF', 'Cádiz', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/700.png'),
(701, 'Eibar', 'SD Eibar', 'Eibar', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/701.png'),
(702, 'Elche', 'Elche CF', 'Elche', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/702.png'),
(707, 'Tenerife', 'CD Tenerife', 'Santa Cruz de Tenerife', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/707.png'),
(708, 'Almería', 'UD Almería', 'Almería', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/708.png'),
(712, 'Leganés', 'CD Leganés', 'Leganés', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/712.png'),
(713, 'Rayo Vallecano', 'Rayo Vallecano', 'Madrid', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/713.png'),
(714, 'Las Palmas', 'UD Las Palmas', 'Las Palmas de Gran Canaria', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/714.png'),
(723, 'Real Sociedad B', 'Real Sociedad de Fútbol B', 'San Sebastian', 724, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/2719_120x120.png'),
(737, 'Burgos', 'Burgos CF', 'Burgos', 724, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/4080_120x120.png'),
(740, 'Ponferradina', 'SD Ponferradina', 'Ponferrada', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/740.png'),
(741, 'Alcorcón', 'AD Alcorcón', 'Alcorcón', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/741.png'),
(743, 'Fuenlabrada', 'CF Fuenlabrada', 'Fuenlabrada', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/743.png'),
(756, 'Girona', 'Girona FC', 'Girona', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/756.png'),
(757, 'Castellón', 'CD Castellón', 'Castellón de la Plana', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/757.png'),
(766, 'Sabadell', 'CE Sabadell FC', 'Sabadell', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/766.png'),
(789, 'Real Oviedo', 'Real Oviedo', 'Oviedo', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/789.png'),
(802, 'Huesca', 'SD Huesca', 'Huesca', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/802.png'),
(807, 'Cartagena', 'FC Cartagena', 'Cartagena', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/807.png'),
(846, 'Granada', 'Granada CF', 'Granada', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/846.png'),
(847, 'Lugo', 'CD Lugo', 'Lugo', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/847.png'),
(926, 'Amorebieta', 'SD Amorebieta', 'Amorebieta-Echano', 724, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/4127_120x120.png'),
(999, 'Mirandés', 'CD Mirandés', 'Miranda de Ebro', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/999.png'),
(1144, 'UD Logroñés', 'UD Logroñés', 'Logroño', 724, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1144.png'),
(1609, 'Arsenal', 'Arsenal FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1609.png'),
(1610, 'Chelsea', 'Chelsea FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1610.png'),
(1611, 'Manchester United', 'Manchester United FC', 'Manchester', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1611.png'),
(1612, 'Liverpool', 'Liverpool FC', 'Liverpool', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1612.png'),
(1613, 'Newcastle United', 'Newcastle United FC', 'Newcastle upon Tyne', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1613.png'),
(1614, 'Aston Villa', 'Aston Villa FC', 'Birmingham', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1614.png'),
(1616, 'Fulham', 'Fulham FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1616.png'),
(1618, 'Birmingham City', 'Birmingham City FC', 'Birmingham', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1618.png'),
(1619, 'Southampton', 'Southampton FC', 'Southampton, Hampshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1619.png'),
(1620, 'Middlesbrough', 'Middlesbrough FC', 'Middlesbrough', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1620.png'),
(1621, 'Blackburn Rovers', 'Blackburn Rovers FC', 'Blackburn, Lancashire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1621.png'),
(1623, 'Everton', 'Everton FC', 'Liverpool', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1623.png'),
(1624, 'Tottenham Hotspur', 'Tottenham Hotspur FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1624.png'),
(1625, 'Manchester City', 'Manchester City FC', 'Manchester', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1625.png'),
(1626, 'Norwich City', 'Norwich City FC', 'Norwich, Norfolk', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1626.png'),
(1627, 'West Bromwich Albion', 'West Bromwich Albion FC', 'West Bromwich', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1627.png'),
(1628, 'Crystal Palace', 'Crystal Palace FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1628.png'),
(1629, 'Wolverhampton Wanderers', 'Wolverhampton Wanderers FC', 'Wolverhampton', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1629.png'),
(1630, 'Leeds United', 'Leeds United FC', 'Leeds, West Yorkshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1630.png'),
(1631, 'Leicester City', 'Leicester City FC', 'Leicester', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1631.png'),
(1633, 'West Ham United', 'West Ham United FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1633.png'),
(1636, 'Sheffield United', 'Sheffield United FC', 'Sheffield', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1636.png'),
(1637, 'Reading', 'Reading FC', 'Reading, Berkshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1637.png'),
(1638, 'Millwall', 'Millwall FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1638.png'),
(1639, 'Stoke City', 'Stoke City FC', 'Stoke-on-Trent', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1639.png'),
(1640, 'Coventry City', 'Coventry City FC', 'Coventry', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1640.png'),
(1641, 'Preston North End', 'Preston North End FC', 'Preston', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1641.png'),
(1642, 'Nottingham Forest', 'Nottingham Forest FC', 'Nottingham', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1642.png'),
(1643, 'Rotherham United', 'Rotherham United FC', 'Rotherham', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1643.png'),
(1644, 'Watford', 'Watford FC', 'Watford', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1644.png'),
(1646, 'Burnley', 'Burnley FC', 'Burnley, Lancashire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1646.png'),
(1647, 'Derby County', 'Derby County FC', 'Derby', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1647.png'),
(1650, 'Queens Park Rangers', 'Queens Park Rangers FC', 'London', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1650.png'),
(1651, 'Brighton & Hove Albion', 'Brighton & Hove Albion FC', 'Brighton, East Sussex', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1651.png'),
(1655, 'Bristol City', 'Bristol City FC', 'Bristol', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1655.png'),
(1659, 'Bournemouth', 'AFC Bournemouth', 'Bournemouth, Dorset', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1659.png'),
(1660, 'Luton Town', 'Luton Town FC', 'Luton, Bedfordshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1660.png'),
(1663, 'Barnsley', 'Barnsley FC', 'Barnsley, South Yorkshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1663.png'),
(1664, 'Blackpool', 'Blackpool FC', 'Blackpool, Lancashire', 826, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/322_120x120.png'),
(1666, 'Sheffield Wednesday', 'Sheffield Wednesday FC', 'Sheffield', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1666.png'),
(1668, 'Peterborough United', 'Peterborough United FC', 'Peterborough', 826, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/871_120x120.png'),
(1669, 'Brentford', 'Brentford FC', 'Brentford, Middlesex', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1669.png'),
(1672, 'Hull City', 'Hull City AFC', 'Hull', 826, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/317_120x120.png'),
(1673, 'Huddersfield Town', 'Huddersfield Town FC', 'Huddersfield, West Yorkshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1673.png'),
(1678, 'Wycombe Wanderers', 'Wycombe Wanderers FC', 'High Wycombe, Buckinghamshire', 826, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/1678.png'),
(2443, 'Werder Bremen', 'SV Werder Bremen', 'Bremen', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2443.png'),
(2444, 'Bayern München', 'FC Bayern München', 'München', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2444.png'),
(2445, 'Stuttgart', 'VfB Stuttgart 1893', 'Stuttgart', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2445.png'),
(2446, 'Bayer Leverkusen', 'TSV Bayer 04 Leverkusen', 'Leverkusen', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2446.png'),
(2447, 'Borussia Dortmund', 'BV Borussia 09 Dortmund', 'Dortmund', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2447.png'),
(2448, 'Bochum', 'VfL Bochum 1848', 'Bochum', 276, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/97_120x120.png'),
(2449, 'Schalke 04', 'FC Schalke 04', 'Gelsenkirchen', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2449.png'),
(2451, 'Wolfsburg', 'VfL Wolfsburg', 'Wolfsburg', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2451.png'),
(2453, 'Freiburg', 'SC Freiburg', 'Freiburg im Breisgau', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2453.png'),
(2454, 'Borussia M\'gladbach', 'Borussia VfL Mönchengladbach', 'Mönchengladbach', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2454.png'),
(2457, 'Hertha BSC', 'Hertha BSC', 'Berlin', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2457.png'),
(2459, 'Arminia Bielefeld', 'DSC Arminia Bielefeld', 'Bielefeld', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2459.png'),
(2460, 'Mainz 05', '1. FSV Mainz 05', 'Mainz', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2460.png'),
(2462, 'Eintracht Frankfurt', 'Eintracht Frankfurt', 'Frankfurt am Main', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2462.png'),
(2463, 'Köln', '1. FC Köln', 'Köln', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2463.png'),
(2469, 'Greuther Fürth', 'SpVgg Greuther Fürth', 'Fürth', 276, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/333_120x120.png'),
(2481, 'Augsburg', 'FC Augsburg', 'Augsburg', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2481.png'),
(2482, 'Hoffenheim', 'TSG 1899 Hoffenheim', 'Sinsheim', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2482.png'),
(2500, 'Union Berlin', '1. FC Union Berlin', 'Berlin', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2500.png'),
(2975, 'RB Leipzig', 'Rasen Ballsport Leipzig', 'Leipzig', 276, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/2975.png'),
(3157, 'Milan', 'AC Milan', 'Milano', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3157.png'),
(3158, 'Roma', 'AS Roma', 'Roma', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3158.png'),
(3159, 'Juventus', 'Juventus FC', 'Torino', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3159.png'),
(3160, 'Parma', 'Parma Calcio 1913', 'Parma', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3160.png'),
(3161, 'Internazionale', 'FC Internazionale Milano', 'Milano', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3161.png'),
(3162, 'Lazio', 'SS Lazio', 'Formello', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3162.png'),
(3163, 'Udinese', 'Udinese Calcio', 'Udine', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3163.png'),
(3164, 'Sampdoria', 'UC Sampdoria', 'Genova', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3164.png'),
(3166, 'Bologna', 'Bologna FC 1909', 'Bologna', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3166.png'),
(3172, 'Atalanta', 'Atalanta Bergamasca Calcio', 'Ciserano', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3172.png'),
(3173, 'Cagliari', 'Cagliari Calcio', 'Cagliari', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3173.png'),
(3176, 'Fiorentina', 'ACF Fiorentina', 'Firenze', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3176.png'),
(3185, 'Torino', 'Torino FC', 'Torino', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3185.png'),
(3187, 'Napoli', 'SSC Napoli', 'Castel Volturno', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3187.png'),
(3193, 'Genoa', 'Genoa CFC', 'Genova', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3193.png'),
(3194, 'Hellas Verona', 'Hellas Verona FC', 'Verona', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3194.png'),
(3197, 'Crotone', 'FC Crotone', 'Crotone', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3197.png'),
(3205, 'Spezia', 'Spezia Calcio', 'La Spezia', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3205.png'),
(3219, 'Benevento', 'Benevento Calcio', 'Benevento', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3219.png'),
(3315, 'Sassuolo', 'US Sassuolo Calcio', 'Sassuolo', 380, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3315.png'),
(3766, 'Olympique Lyonnais', 'Olympique Lyonnais', 'Lyon', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3766.png'),
(3767, 'PSG', 'Paris Saint-Germain FC', 'Paris', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3767.png'),
(3770, 'Nantes', 'FC Nantes', 'La Chapelle-sur-Erdre', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3770.png'),
(3771, 'Olympique Marseille', 'Olympique de Marseille', 'Marseille', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3771.png'),
(3772, 'Bordeaux', 'FC Girondins de Bordeaux', 'Le Haillan', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3772.png'),
(3773, 'Lens', 'Racing Club de Lens', 'Avion', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3773.png'),
(3774, 'Rennes', 'Stade Rennais FC', 'Rennes', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3774.png'),
(3775, 'Nice', 'O.G.C. Nice Côte d\'Azur', 'Nice', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3775.png'),
(3776, 'Lille', 'Lille OSC Métropole', 'Villeneuve-d\'Ascq', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3776.png'),
(3777, 'Metz', 'FC Metz', 'Metz', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3777.png'),
(3779, 'Strasbourg', 'RC Strasbourg Alsace', 'Strasbourg', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3779.png'),
(3782, 'Saint-Étienne', 'AS Saint-Étienne', 'Saint-Étienne', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3782.png'),
(3787, 'Montpellier', 'Montpellier HSC', 'Montpellier', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3787.png'),
(3788, 'Lorient', 'FC Lorient', 'Ploemeur', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3788.png'),
(3795, 'Troyes', 'Espérance Sportive Troyes Aube Champagne', 'Troyes', 250, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/560_120x120.png'),
(3797, 'Clermont', 'Clermont Foot 63', 'Clermont-Ferrand', 250, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/561_120x120.png'),
(3799, 'Angers SCO', 'Angers Sporting Club de L\'Ouest', 'Angers', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3799.png'),
(3802, 'Reims', 'Stade de Reims', 'Reims', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3802.png'),
(3803, 'Brest', 'Stade Brestois 29', 'Brest', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3803.png'),
(3804, 'Dijon', 'Dijon FCO', 'Dijon', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3804.png'),
(3813, 'Nîmes', 'Nîmes Olympique', 'Nîmes', 250, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/3813.png'),
(5638, 'São Paulo', 'São Paulo FC', 'São Paulo, São Paulo', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5638.png'),
(5643, 'Goiás', 'Goiás EC', 'Goiânia, Goiás', 76, 'club', 'male', ''),
(5644, 'Internacional', 'SC Internacional', 'Porto Alegre, Rio Grande do Sul', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5644.png'),
(5646, 'Palmeiras', 'SE Palmeiras', 'São Paulo, São Paulo', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5646.png'),
(5648, 'Fluminense', 'Fluminense FC', 'Rio de Janeiro, Rio de Janeiro', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5648.png'),
(5649, 'Grêmio', 'Grêmio FB Porto Alegrense', 'Porto Alegre, Rio Grande do Sul', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5649.png'),
(5650, 'Juventude', 'EC Juventude', 'Caxias do Sul, Rio Grande do Sul', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5650.png'),
(5651, 'Athletico Paranaense', 'Club Athletico Paranaense', 'Curitiba, Paraná', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5651.png'),
(5653, 'Atlético Mineiro', 'CA Mineiro', 'Belo Horizonte, Minas Gerais', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5653.png'),
(5654, 'Flamengo', 'CR Flamengo', 'Rio de Janeiro, Rio de Janeiro', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5654.png'),
(5655, 'Santos', 'Santos FC São Paulo', 'Santos, São Paulo', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5655.png'),
(5656, 'Corinthians', 'SC Corinthians Paulista', 'São Paulo', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5656.png'),
(5657, 'Vasco da Gama', 'CR Vasco da Gama', 'Rio de Janeiro, Rio de Janeiro', 76, 'club', 'male', ''),
(5659, 'Botafogo', 'Botafogo FR', 'Rio de Janeiro, Rio de Janeiro', 76, 'club', 'male', ''),
(5660, 'Coritiba', 'Coritiba FBC', 'Curitiba, Paraná', 76, 'club', 'male', ''),
(5663, 'Fortaleza', 'Fortaleza EC', 'Fortaleza, Ceará', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5663.png'),
(5669, 'Ceará', 'Ceará SC', 'Fortaleza, Ceará', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5669.png'),
(5673, 'América Mineiro', 'América FC (Minas Gerais)', 'Belo Horizonte, Minas Gerais', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5673.png'),
(5674, 'Sport Recife', 'SC do Recife', 'Recife, Pernambuco', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5674.png'),
(5677, 'Bahia', 'EC Bahia', 'Salvador, Bahia', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5677.png'),
(5685, 'Red Bull Bragantino', 'Red Bull Bragantino', 'Bragança Paulista, São Paulo', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5685.png'),
(5707, 'Cuiabá', 'Cuiabá EC', 'Cuiabá, Mato Grosso', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5707.png'),
(5812, 'Atlético GO', 'AC Goianiense', 'Goiânia, Goiás', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5812.png'),
(5819, 'Chapecoense', 'Chapecoense AF', 'Chapecó, Santa Catarina', 76, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/5819.png'),
(7847, 'Los Angeles Galaxy', 'Los Angeles Galaxy', 'Los Angeles, California', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7847.png'),
(7848, 'Chicago Fire', 'Chicago Fire', 'Bridgeview, Illinois', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7848.png'),
(7849, 'Sporting KC', 'Sporting Kansas City', 'Kansas City, Kansas', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7849.png'),
(7851, 'SJ Earthquakes', 'San Jose Earthquakes', 'Santa Clara, California', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7851.png'),
(7852, 'DC United', 'DC United', 'Washington, District of Columbia', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7852.png'),
(7853, 'Colorado Rapids', 'Colorado Rapids', 'Denver, Colorado', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7853.png'),
(7854, 'New England', 'New England Revolution', 'Foxborough, Massachusetts', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7854.png'),
(7855, 'Columbus Crew', 'Columbus Crew', 'Columbus, Ohio', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7855.png'),
(7869, 'Dallas', 'FC Dallas', 'Frisco, Texas', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7869.png'),
(7871, 'Real Salt Lake', 'Real Salt Lake', 'Salt Lake City, Utah', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7871.png'),
(7944, 'Houston Dynamo', 'Houston Dynamo', 'Houston, Texas', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7944.png'),
(7945, 'New York RB', 'New York Red Bulls', 'Secaucus, New Jersey', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/7945.png'),
(8061, 'Philadelphia Union', 'Philadelphia Union', 'Chester, Pennsylvania', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8061.png'),
(8067, 'Seattle Sounders', 'Seattle Sounders FC', 'Renton, Washington', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8067.png'),
(8068, 'Orlando City', 'Orlando City SC', 'Lake Mary, Florida', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8068.png'),
(8095, 'Minnesota United', 'Minnesota United FC', 'Minneapolis-Saint Paul, Minnesota', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8095.png'),
(8113, 'Portland Timbers', 'Portland Timbers', 'Portland, Oregon', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8113.png'),
(8142, 'CF Montréal', 'CF Montréal', 'Montreal, Quebec', 124, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/8142.png'),
(9606, 'Porto', 'FC Porto', 'Porto', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9606.png'),
(9607, 'Benfica', 'SL Benfica', 'Lisboa', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9607.png'),
(9608, 'Sporting CP', 'Sporting Clube de Portugal', 'Lisboa', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9608.png'),
(9609, 'Nacional', 'CD Nacional Funchal', 'Funchal (Ilha da Madeira)', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9609.png'),
(9610, 'Sporting Braga', 'Sporting Braga', 'Braga', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9610.png'),
(9611, 'Rio Ave', 'Rio Ave FC', 'Vila do Conde', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9611.png'),
(9612, 'Marítimo', 'CS Marítimo Funchal', 'Funchal (Ilha da Madeira)', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9612.png'),
(9613, 'Boavista', 'Boavista FC', 'Porto', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9613.png'),
(9615, 'Moreirense', 'Moreirense FC', 'Moreira de Cónegos', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9615.png'),
(9617, 'Vitória Guimarães', 'Vitória Guimarães SC', 'Guimarães', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9617.png'),
(9620, 'Belenenses', 'Os Belenenses SAD', 'Lisboa', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9620.png'),
(9621, 'Paços de Ferreira', 'FC Paços de Ferreira', 'Paços de Ferreira', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9621.png'),
(9623, 'Estoril', 'GD Estoril Praia', 'Estoril', 620, 'club', 'male', ''),
(9634, 'Santa Clara', 'CD Santa Clara', 'Ponta Delgada (Ilha de São Miguel, Açores)', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9634.png'),
(9638, 'Portimonense', 'Portimonense SC', 'Portimão', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9638.png'),
(9657, 'Farense', 'SC Farense', 'Faro', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9657.png'),
(9683, 'Vizela', 'FC Vizela', 'Caldas de Vizela', 620, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/1547_120x120.png'),
(9700, 'Gil Vicente', 'Gil Vicente FC', 'Barcelos', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9700.png'),
(9702, 'Famalicão', 'FC Famalicão', 'Vila Nova de Famalicão', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9702.png'),
(9789, 'Arouca', 'FC Arouca', 'Arouca', 620, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/2598_120x120.png'),
(9813, 'Tondela', 'CD Tondela', 'Tondela', 620, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/9813.png'),
(10469, 'Aurora', 'Club Aurora', 'Cochabamba', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10469.png'),
(10470, 'Santa Cruz', 'Real Santa Cruz', '', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10470.png'),
(10472, 'The Strongest', 'Club The Strongest', 'La Paz', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10472.png'),
(10473, 'Oriente Petrolero', 'CD Oriente Petrolero', 'Santa Cruz de la Sierra', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10473.png'),
(10474, 'Bolívar', 'Club Bolívar', 'La Paz', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10474.png'),
(10475, 'San José', 'CD San José', 'Oruro', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10475.png'),
(10476, 'Wilstermann', 'Club Jorge Wilstermann', 'Cochabamba', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10476.png'),
(10477, 'Blooming', 'Club Blooming', 'Santa Cruz de la Sierra', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10477.png'),
(10478, 'Real Potosí', 'Club Real Potosí', 'Potosí', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10478.png'),
(10486, 'Nacional Potosí', 'CA Nacional Potosí', 'Potosí', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10486.png'),
(10487, 'Guabirá', 'CD Guabirá', 'Santa Cruz', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10487.png'),
(10529, 'Cardiff City', 'Cardiff City FC', 'Cardiff', 1013, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10529.png'),
(10531, 'Swansea City', 'Swansea City AFC', 'Swansea', 1013, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/10531.png'),
(12054, 'Arsenal', 'Arsenal de Sarandí', 'Avellaneda, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12054.png'),
(12055, 'Atlético Rafaela', 'Atlético de Rafaela', 'Rafaela, Provincia de Santa Fe', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12055.png'),
(12056, 'Banfield', 'CA Banfield', 'Lomas de Zamora, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12056.png'),
(12057, 'Boca Juniors', 'CA Boca Juniors', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12057.png'),
(12058, 'Chacarita Juniors', 'CA Chacarita Juniors', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12058.png'),
(12059, 'Colón', 'Colón de Santa Fe', 'Ciudad de Santa Fé, Provincia de Santa Fe', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12059.png'),
(12060, 'Estudiantes', 'Estudiantes de La Plata', 'La Plata, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12060.png'),
(12061, 'Gimnasia La Plata', 'Gimnasia y Esgrima La Plata', 'La Plata, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12061.png'),
(12062, 'Independiente', 'CA Independiente', 'Avellaneda, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12062.png'),
(12063, 'Lanús', 'CA Lanús', 'Lanús, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12063.png'),
(12064, 'Newell\'s Old Boys', 'Newell\'s Old Boys', 'Rosario, Santa Fe', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12064.png'),
(12065, 'Nueva Chicago', 'CA Nueva Chicago', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12065.png'),
(12067, 'Quilmes', 'Quilmes AC', 'Quilmes, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12067.png'),
(12068, 'Racing Club', 'Racing Club de Avellaneda', 'Avellaneda, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12068.png'),
(12069, 'River Plate', 'CA River Plate', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12069.png'),
(12070, 'Rosario Central', 'CA Rosario Central', 'Rosario, Provincia de Santa Fe', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12070.png'),
(12071, 'San Lorenzo', 'CA San Lorenzo de Almagro', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12071.png'),
(12072, 'Talleres Córdoba', 'CA Talleres de Córdoba', 'Ciudad de Córdoba, Provincia de Córdoba', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12072.png'),
(12073, 'Vélez Sarsfield', 'Club Atlético Vélez Sarsfield', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12073.png'),
(12074, 'Almagro', 'Club Almagro', 'Tres de Febrero, Provincia de Buenos', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12074.png'),
(12075, 'Argentinos Juniors', 'Argentinos Juniors', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12075.png'),
(12076, 'Belgrano', 'CA Belgrano de Córdoba', 'Ciudad de Córdoba, Provincia de Córdoba', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12076.png'),
(12078, 'Defensores de Belgrano', 'CA Defensores de Belgrano', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12078.png'),
(12079, 'Defensa y Justicia', 'CSD Defensa y Justicia', 'Florencio Varela, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12079.png'),
(12081, 'Ferro Carril Oeste', 'Club Ferro Carril Oeste', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12081.png'),
(12083, 'Gimnasia Jujuy', 'Gimnasia y Esgrima de Jujuy', 'San Salvador de Jujuy, Provincia de Jujuy', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12083.png'),
(12084, 'Godoy Cruz', 'Godoy Cruz Antonio Tomba', 'Godoy Cruz, Provincia de Mendoza', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12084.png'),
(12085, 'Huracán', 'CA Huracán', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12085.png'),
(12087, 'Instituto', 'Instituto AC Córdoba', 'Ciudad de Córdoba, Provincia de Córdoba', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12087.png'),
(12091, 'San Martín San Juan', 'CA San Martín de San Juan', 'San Juan, Provincia de San Juan', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12091.png'),
(12093, 'Unión Santa Fe', 'CA Unión de Santa Fe', 'Ciudad de Santa Fé, Provincia de Santa Fe', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12093.png'),
(12095, 'Sarmiento', 'CA Sarmiento', 'Junín, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12095.png'),
(12096, 'Aldosivi', 'CA Aldosivi', 'Mar del Plata, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12096.png'),
(12098, 'Tigre', 'CA Tigre', 'Victoria, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12098.png'),
(12099, 'Platense', 'CA Platense', 'Vicente López, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12099.png'),
(12100, 'San Martín Tucumán', 'CA San Martín de Tucumán', 'San Miguel de Tucumán, Provincia de Tucumán', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12100.png'),
(12102, 'All Boys', 'CA All Boys', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12102.png'),
(12103, 'Almirante Brown', 'Club Almirante Brown', 'San Justo, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12103.png'),
(12105, 'Brown de Adrogué', 'CA Brown de Adrogué', 'Almirante Brown, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12105.png'),
(12106, 'Atlanta', 'CA Atlanta', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12106.png'),
(12110, 'Estudiantes Caseros', 'CA Estudiantes de Caseros', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12110.png'),
(12115, 'Deportivo Morón', 'CD Morón', 'Morón, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12115.png'),
(12116, 'San Telmo', 'CA San Telmo', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12116.png'),
(12117, 'Tristán Suárez', 'CSyD Tristán Suárez', 'Ezeiza, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12117.png'),
(12119, 'Temperley', 'CA Temperley', 'Temperley, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12119.png'),
(12125, 'Deportivo Santamarina', 'CD Santamarina de Tandil', 'Tandil, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12125.png'),
(12126, 'Guillermo Brown', 'Club Social y Atlético Guillermo Brown de Puerto Madryn', 'Puerto Madryn, Provincia de Chubut', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12126.png'),
(12129, 'Gimnasia Mendoza', 'Atlético Gimnasia y Esgrima de Mendoza', 'Mendoza, Provincia de Mendoza', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12129.png'),
(12132, 'Independiente Rivadavia', 'CS Independiente Rivadavia', 'Mendoza, Provincia de Mendoza', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12132.png'),
(12136, 'Atlético Tucumán', 'CA Tucuman', 'San Miguel de Tucumán, Provincia de Tucumán', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12136.png'),
(12148, 'Barracas Central', 'CA Barracas Central', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12148.png'),
(12152, 'Villa Dálmine', 'Club Villa Dálmine', 'Campana, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12152.png'),
(12176, 'Deportivo Riestra', 'CD Riestra', 'Capital Federal, Ciudad de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12176.png'),
(12182, 'Alvarado', 'Club Atlético Alvarado Mar del Plata', 'Mar del Plata, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12182.png'),
(12184, 'Deportivo Maipú', 'CD Maipú', 'Maipú, Provincia de Mendoza', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12184.png'),
(12185, 'Estudiantes Río Cuarto', 'AA Estudiantes de Río Cuarto', 'Río Cuarto, Provincia de Córdoba', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12185.png'),
(12190, 'Central Córdoba SdE', 'CA Central Córdoba de Santiago del Estero', 'Santiago del Estero, Provincia de Santiago del Estero', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12190.png'),
(12210, 'Patronato', 'CA Patronato de la Juventud Católica', 'Paraná, Provincia de Entre Ríos', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12210.png'),
(12247, 'San Lorenzo', 'Club Atlético San Lorenzo de Almagro', 'Buenos Aires', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12247.png'),
(12254, 'Boca Juniors', 'Club Atlético Boca Juniors', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12254.png'),
(12259, 'Club Atlético Mitre', 'Club Atlético Mitre de Santiago del Estero', 'Santiago del Estero, Provincia de Santiago del Estero', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12259.png'),
(12283, 'Cobreloa', 'CD Cobreloa', 'Calama', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12283.png'),
(12284, 'Santiago Wanderers', 'CD Santiago Wanderers', 'Valparaíso', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12284.png'),
(12285, 'Univ. Concepción', 'CD Universidad de Concepción', 'Concepción', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12285.png'),
(12286, 'Huachipato', 'CD Huachipato', 'Talcahuano', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12286.png'),
(12287, 'Coquimbo Unido', 'CD Coquimbo Unido', 'Coquimbo', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12287.png'),
(12288, 'Colo Colo', 'CSD Colo Colo', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12288.png'),
(12289, 'Universidad de Chile', 'CFP Universidad de Chile', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12289.png'),
(12290, 'Unión Española', 'Unión Española', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12290.png'),
(12291, 'Deportes Temuco', 'CD Temuco', 'Temuco', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12291.png'),
(12292, 'Audax Italiano', 'Audax Italiano La Florida SADP', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12292.png'),
(12293, 'Everton', 'Everton de Viña del Mar', 'Viña del Mar', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12293.png'),
(12294, 'La Serena', 'CD La Serena', 'La Serena', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12294.png'),
(12295, 'Universidad Católica', 'CD Universidad Católica', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12295.png'),
(12296, 'Unión San Felipe', 'CD Unión San Felipe', 'San Felipe', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12296.png'),
(12297, 'Puerto Montt', 'CD Puerto Montt', 'Puerto Montt', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12297.png'),
(12298, 'Rangers', 'CSD Rangers', 'Talca', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12298.png'),
(12299, 'Palestino', 'CD Palestino', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12299.png'),
(12300, 'Cobresal', 'CD Cobresal', 'El Salvador, comuna Diego de Almagro', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12300.png'),
(12302, 'O\'Higgins', 'CD O\'Higgins', 'Rancagua', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12302.png'),
(12303, 'Santiago Morning', 'CD Santiago Morning', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12303.png'),
(12305, 'Melipilla', 'CD Melipilla', 'Melipilla', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12305.png'),
(12307, 'Antofagasta', 'CD Antofagasta', 'Antofagasta', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12307.png'),
(12308, 'Copiapó', 'CD Copiapó', 'Copiapó', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12308.png'),
(12309, 'Fernández Vial', 'CD Arturo Fernández Vial', 'Concepción', 152, 'club', 'male', ''),
(12311, 'Ñublense', 'Deportivo Ñublense SADP', 'Chillán', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12311.png'),
(12312, 'Curicó Unido', 'CD Provincial Curicó Unido', 'Curicó', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12312.png'),
(12313, 'San Luis', 'CD San Luis de Quillota', 'Quillota', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12313.png'),
(12314, 'Unión La Calera', 'CD Unión La Calera', 'La Calera', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12314.png'),
(12315, 'Deportes Iquique', 'Club Deportes Iquique', 'Iquique', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12315.png'),
(12317, 'San Marcos', 'CD San Marcos de Arica', 'Arica', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12317.png'),
(12321, 'Magallanes', 'Club Deportivo Magallanes', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12321.png'),
(12330, 'Barnechea', 'Club Social y Deportivo Lo Barnechea', 'Santiago de Chile', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12330.png'),
(12334, 'Deportes Santa Cruz', 'Deportes Santa Cruz', 'Santa Cruz', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12334.png'),
(12371, 'Lautaro de Buin ', 'Lautaro de Buin ', '', 152, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12371.png'),
(12390, 'América de Cali', 'Sociedad Anónima Deportiva América S.A.', 'Santiago de Cali', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12390.png');
INSERT IGNORE INTO `set_teams` (`id`, `name`, `officialName`, `city`, `country_id`, `level`, `gender`, `image`) VALUES
(12391, 'Atlético Nacional', 'Club Atlético Nacional SA', 'Medellín', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12391.png'),
(12392, 'Once Caldas', 'Once Caldas SA', 'Manizales', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12392.png'),
(12393, 'Junior', 'Club Deportivo Junior FC S.A.', 'Barranquilla', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12393.png'),
(12394, 'Deportivo Cali', 'Asociación Deportivo Cali', 'Santiago de Cali', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12394.png'),
(12395, 'Deportivo Pereira', 'Corporación Social Deportiva y Cultural de Pereira', 'Pereira', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12395.png'),
(12396, 'Deportes Tolima', 'Club Deportes Tolima S.A.', 'Ibagué', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12396.png'),
(12397, 'Deportivo Pasto', 'Asociación Deportivo Pasto', 'San Juan de Pasto', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12397.png'),
(12398, 'Boyacá Chicó', 'Deportivo Boyacá Chicó FC S.A.', 'Tunja', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12398.png'),
(12399, 'Medellín', 'Deportivo Independiente Medellín S.A.', 'Medellín', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12399.png'),
(12400, 'Millonarios', 'Millonarios FC SA', 'Bogotá, D.C.', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12400.png'),
(12401, 'Atlético Bucaramanga', 'Club Atlético Bucaramanga CD', 'Bucaramanga', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12401.png'),
(12403, 'Atlético Huila', 'Club Deportivo Atlético Huila', 'Neiva', 170, 'club', 'male', ''),
(12404, 'Santa Fe', 'Club Independiente Santa Fe', 'Bogotá, D.C.', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12404.png'),
(12405, 'Envigado', 'Envigado FC', 'Envigado', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12405.png'),
(12406, 'Deportes Quindío', 'Corporación Deportes Quindío', 'Armenia', 170, 'club', 'male', ''),
(12411, 'La Equidad', 'Club Deportivo La Equidad Seguros', 'Bogotá, D.C.', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12411.png'),
(12413, 'Rionegro Águilas', 'Rionegro Águilas S.A.', 'Itagüí', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12413.png'),
(12421, 'Patriotas Boyacá', 'Corporación Deportiva Patriotas FC', 'Tunja', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12421.png'),
(12425, 'Alianza Petrolera', 'Corporación Deportiva Alianza Petrolera', 'Barrancabermeja', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12425.png'),
(12508, 'Panathinaikos', 'Panathinaikos FC', 'Athína (Athens)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12508.png'),
(12509, 'Olympiacos Piraeus', 'Olympiacos F.C.', 'Pireás (Piraeus)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12509.png'),
(12510, 'PAOK', 'PAOK Thessaloniki FC', 'Thessaloníki', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12510.png'),
(12511, 'AEK Athens', 'AEK Athens FC', 'Athína (Athens)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12511.png'),
(12517, 'OFI', 'OFI FC', 'Iraklio (Heraklion)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12517.png'),
(12520, 'Aris', 'Aris Thessaloniki FC', 'Thessaloníki', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12520.png'),
(12532, 'Apollon Smirnis', 'Apollon Smirnis FC', 'Athína (Athens)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12532.png'),
(12536, 'Atromitos', 'PAE APS Atromitos Athens', 'Athína (Athens)', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12536.png'),
(12537, 'PAS Giannina', 'PAS Giannina FC', 'Ioannina', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12537.png'),
(12539, 'Larissa', 'AE Larissa', 'Larissa', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12539.png'),
(12567, 'Panetolikos FC', 'Panetolikos FC', 'Agrinio', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12567.png'),
(12584, 'Lamia', 'PAS Lamia 1964', '', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12584.png'),
(12603, 'Asteras Tripolis', 'Asteras Tripolis FC', 'Tripoli', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/12603.png'),
(14995, 'Toronto', 'Toronto FC', 'Toronto', 124, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/14995.png'),
(15015, 'Vancouver Whitecaps', 'Vancouver Whitecaps FC', 'Vancouver, British Columbia', 124, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15015.png'),
(15405, 'América', 'Club América', 'Ciudad de México, D.F.', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15405.png'),
(15406, 'Atlante', 'CF Atlante', 'Benito Juárez', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/907_120x120.png'),
(15407, 'Atlas', 'CSyD Atlas de Guadalajara', 'Guadalajara', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15407.png'),
(15408, 'Cruz Azul', 'Cruz Azul FC', 'Ciudad de México (D.F.)', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15408.png'),
(15409, 'Guadalajara', 'CD Guadalajara', 'Zapopan, Guadalajara', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15409.png'),
(15411, 'Atlético Morelia', 'Club Atlético Morelia', 'Morelia', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/913_120x120.png'),
(15412, 'Necaxa', 'Club Necaxa', 'Aguascalientes', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15412.png'),
(15413, 'Pachuca', 'CF Pachuca', 'Pachuca de Soto', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15413.png'),
(15414, 'Puebla', 'Puebla FC', 'Puebla', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15414.png'),
(15415, 'Santos Laguna', 'Club Santos Laguna', 'Torreón', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15415.png'),
(15417, 'Tigres UANL', 'CF Tigres de la Universidad Autónoma de Nuevo León', 'San Nicolás de los Garza', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15417.png'),
(15418, 'Toluca', 'Deportivo Toluca FC', 'Toluca de Lerdo', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15418.png'),
(15420, 'Pumas UNAM', 'Pumas de la Universidad Nacional Autonoma de Mexico', 'Delegación Coyoacán, Ciudad de México (D.F.)', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15420.png'),
(15421, 'Querétaro', 'Querétaro FC', 'Queretaro', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15421.png'),
(15424, 'León', 'Club León', 'León de los Aldamas', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15424.png'),
(15426, 'Celaya', 'Celaya CF', 'Celaya', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/4433_120x120.png'),
(15428, 'Venados', 'Venados FC', 'Mérida, Yucatán', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/3435_120x120.png'),
(15429, 'Alebrijes de Oaxaca', 'CF Alebrijes de Oaxaca', 'Zacatepec', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g1482_120x120.png'),
(15440, 'Correcaminos UAT', 'Correcaminos de la UAT', 'Ciudad Victoria', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/3254_120x120.png'),
(15441, 'Universidad Guadalajara', 'Club Leones Negros de la Universidad de Guadalajara', 'Guadalajara', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g1494_120x120.png'),
(15444, 'Monterrey', 'CF Monterrey', 'Monterrey', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15444.png'),
(15458, 'Tampico Madero', 'Jaibos Tampico Madero', 'Ciudad Madero', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g5109_120x120.png'),
(15459, 'Club Tijuana', 'Club Tijuana Xoloitzcuintles de Caliente', 'Tijuana', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15459.png'),
(15465, 'Dorados', 'CSyD Dorados de Sinaloa', 'Culiacán', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/3253_120x120.png'),
(15482, 'Cerro Porteño', 'Club Cerro Porteño', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15482.png'),
(15483, 'Libertad', 'Club Libertad', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15483.png'),
(15485, 'Guaraní', 'Club Guaraní', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15485.png'),
(15486, 'Olimpia', 'Club Olimpia', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15486.png'),
(15487, 'Sportivo Luqueño', 'Club Sportivo Luqueño', 'Luque', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15487.png'),
(15488, '12 de Octubre', 'Club 12 de Octubre', 'Itauguá', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15488.png'),
(15489, 'Nacional Asunción', 'Club Nacional', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15489.png'),
(15491, 'Sol de América', 'Club Sol de América', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15491.png'),
(15514, 'River Plate', 'Club River Plate', 'Asunción', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15514.png'),
(15526, 'Alianza Lima', 'Club Alianza Lima', 'Lima', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15526.png'),
(15527, 'Alianza Atlético', 'Club Alianza Atlético Sullana', 'Sullana', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15527.png'),
(15528, 'Cienciano', 'Club Cienciano', 'Cusco', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15528.png'),
(15529, 'Universitario', 'Club Universitario de Deportes', 'Lima', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15529.png'),
(15531, 'César Vallejo', 'CD Universidad César Vallejo', 'Trujillo', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15531.png'),
(15532, 'Sporting Cristal', 'Club Sporting Cristal SAC', 'Lima', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15532.png'),
(15534, 'Melgar', 'FBC Melgar', 'Arequipa', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15534.png'),
(15538, 'Sport Boys', 'Sport Boys Association', 'Callao', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15538.png'),
(15539, 'Universidad San Martín', 'CD Universidad San Martín de Porres', 'Lima', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15539.png'),
(15545, 'Deportivo Municipal', 'Club Centro Deportivo Municipal', 'Lima', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15545.png'),
(15549, 'Ayacucho', 'Ayacucho FC', 'Ayacucho (Huamanga)', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15549.png'),
(15551, 'UTC Cajamarca', 'CCyD Universidad Técnica de Cajamarca', 'Cajamarca', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15551.png'),
(15560, 'Sport Huancayo', 'CD Sport Huancayo', 'Huancayo', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15560.png'),
(15562, 'Carlos Mannucci', 'CSD Carlos A. Mannucci', 'Trujillo', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15562.png'),
(15570, 'Alianza Universidad', 'Club Social Deportivo Alianza Universidad', 'Huánuco', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15570.png'),
(15591, 'Cusco', 'Cusco Fútbol Club', 'Cuzco', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15591.png'),
(15631, 'Cerrito', 'Club Sportivo Cerrito', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15631.png'),
(15632, 'Liverpool', 'Liverpool FC Montevideo', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15632.png'),
(15633, 'Peñarol', 'Club Atlético Peñarol', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15633.png'),
(15634, 'Nacional', 'Club Nacional de Football', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15634.png'),
(15637, 'Wanderers', 'Montevideo Wanderers Fútbol Club', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15637.png'),
(15639, 'Rentistas', 'Club Atlético Rentistas', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15639.png'),
(15643, 'Fénix', 'Centro Atlético Fénix', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15643.png'),
(15646, 'Plaza Colonia', 'Club Plaza Colonia de Deportes', 'Colonia del Sacramento', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15646.png'),
(15647, 'Deportivo Maldonado', 'Club Deportivo Maldonado', 'Maldonado', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15647.png'),
(15649, 'River Plate', 'Club Atlético River Plate', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15649.png'),
(15650, 'Villa Española', 'Club Social y Deportivo Villa Española', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15650.png'),
(15653, 'Progreso', 'Club Atlético Progreso', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15653.png'),
(15654, 'Cerro Largo', 'Cerro Largo Fútbol Club', 'Melo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15654.png'),
(15660, 'Sud América', 'Institución Atlética Sud América', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15660.png'),
(15664, 'Boston River', 'Club Atlético Boston River S.A.D.', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15664.png'),
(15680, 'Caracas', 'Caracas FC', 'Caracas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15680.png'),
(15681, 'Carabobo', 'Carabobo FC', 'Valencia', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15681.png'),
(15682, 'Deportivo Táchira', 'Deportivo Táchira FC', 'San Cristóbal', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15682.png'),
(15683, 'Estudiantes de Mérida', 'Estudiantes de Mérida FC', 'Mérida', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15683.png'),
(15684, 'Mineros de Guayana', 'AC Mineros de Guayana', 'Ciudad Guayana', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15684.png'),
(15685, 'Monagas', 'Monagas SC', 'Maturín', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15685.png'),
(15686, 'Trujillanos', 'Trujillanos FC', 'Valera', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15686.png'),
(15691, 'Aragua', 'Aragua FC', 'Maracay', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15691.png'),
(15692, 'Zamora', 'Zamora Fútbol Club', 'Barinas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15692.png'),
(15693, 'Portuguesa', 'Portuguesa FC', 'Acarigua', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15693.png'),
(15698, 'Deportivo Lara', 'CD Lara', 'Barquisimeto', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15698.png'),
(15702, 'Zulia', 'Zulia FC', 'Maracaibo', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15702.png'),
(15714, 'Deportivo La Guaira', 'Deportivo La Guaira', 'Caracas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15714.png'),
(15718, 'Yaracuyanos', 'Yaracuyanos FC', 'San Felipe', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15718.png'),
(15719, 'Atlético Venezuela', 'Atlético Venezuela FC', 'Caracas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15719.png'),
(15742, 'UCV', 'Universidad Central de Venezuela FC', 'Caracas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15742.png'),
(15746, 'Gran Valencia Maracay', 'Gran Valencia FC Maracay', '', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15746.png'),
(15764, 'LDU Quito', 'Liga Deportiva Universitaria de Quito', 'Quito', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15764.png'),
(15765, 'Aucas', 'SD Aucas', 'Quito', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15765.png'),
(15766, 'Emelec', 'CS Emelec', 'Guayaquil', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15766.png'),
(15767, 'Deportivo Cuenca', 'CD Cuenca', 'Cuenca', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15767.png'),
(15770, 'Olmedo', 'CD Olmedo', 'Riobamba', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15770.png'),
(15771, 'Barcelona', 'Barcelona SC', 'Guayaquil', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15771.png'),
(15772, 'Macará', 'CSD Macará', 'Ambato', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15772.png'),
(15775, 'Manta', 'Manta FC', 'Manta', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15775.png'),
(15776, 'Técnico Universitario', 'CD Técnico Universitario', 'Ambato', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15776.png'),
(15780, 'Delfin', 'Delfín S.C.', 'Manta', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15780.png'),
(15782, 'Universidad Católica', 'CD Universidad Católica del Ecuador', 'Quito', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15782.png'),
(15788, 'Independiente del Valle', 'CSD Independiente del Valle', 'Sangolquí', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15788.png'),
(15793, 'Guayaquil City', 'Guayaquil City FC', 'Guayaquil', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15793.png'),
(15806, '9 de Octubre', '9 de Octubre', '', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15806.png'),
(15813, 'Mushuc Runa', 'Mushuc Runa SC', 'Ambato', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/15813.png'),
(19830, 'Monaco', 'AS Monaco FC', 'Monaco', 492, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/19830.png'),
(23073, 'Metropolitanos', 'Metropolitanos FC', 'Caracas', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/23073.png'),
(23208, 'Club Atlético Güemes', 'Club Atlético Güemes de Santiago del Estero', 'Santiago del Estero, Provincia de Santiago del Estero', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/23208.png'),
(23228, 'Agropecuario', 'Club Argentino Agropecuario de Carlos Casares', 'Carlos Casares, Provincia de Buenos Aires', 32, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/23228.png'),
(23497, 'Torque', 'Montevideo City Torque', 'Montevideo', 858, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/23497.png'),
(24191, 'Binacional', 'Deportivo Binacional', '', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/24191.png'),
(24749, 'Jaguares de Córdoba', 'CD Jaguares de Córdoba', 'Montería', 170, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/24749.png'),
(25244, 'River Plate', 'CA River Plate', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25244.png'),
(25245, 'UAI Urquiza', 'CD UAI Urquiza', 'General San Martín, Provincia de buenos Aires', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25245.png'),
(25246, 'Huracán', 'CA Huracán', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25246.png'),
(25247, 'Estudiantes La Plata', 'Club Estudiantes de La Plata', 'La Plata', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25247.png'),
(25248, 'Independiente', 'CA Independiente', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25248.png'),
(25249, 'Excursionistas', 'CA Excursionistas', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25249.png'),
(25250, 'Platense', 'CA Platense', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25250.png'),
(25866, 'Atlético de San Luis', 'Atlético de San Luis', 'San Luis Potosí', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/25866.png'),
(26089, 'Cimarrones de Sonora', 'Cimarrones de Sonora FC', 'Hermosillo', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g25018_120x120.png'),
(26756, 'Villa San Carlos', 'CA Villa San Carlos', 'Berisso, Provincia de Buenos Aires', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/26756.png'),
(30149, 'Nashville SC', 'Nashville SC', '', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/30149.png'),
(30286, 'Mineros de Zacatecas', 'Club Deportivo Mineros de Zacatecas', 'Zacatecas', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g28451_120x120.png'),
(31554, 'Tlaxcala', 'Tlaxcala FC', '', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g30975_120x120.png'),
(32556, 'New York City', 'New York City FC', 'New York, New York', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/32556.png'),
(34402, 'Juárez', 'FC Juárez', 'Ciudad Juárez, Chihuahua', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/34402.png'),
(34676, 'Academia Puerto Cabello', 'Academia Puerto Cabello', 'Puerto Cabello', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/34676.png'),
(35479, 'Tepatitlán de Morelos', 'Tepatitlán de Morelos', 'Tepatitlán de Morelos', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g34012_120x120.png'),
(36698, 'Royal Pari', 'Royal Pari FC', 'Santa Cruz de la Sierra', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/36698.png'),
(36713, 'LALA', 'AC LALA FC', 'Municipio Caroni', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/36713.png'),
(36760, 'Hermanos Colmenares', 'CD Hermanos Colmenares FC', 'Cabudare', 862, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/36760.png'),
(36885, 'Academia Cantolao', 'Academia Deportiva Cantolao', 'Callao', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/36885.png'),
(37892, 'Cincinnati', 'FC Cincinnati', 'Cincinnati, Ohio', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/37892.png'),
(57800, 'El Porvenir', 'Club El Porvenir', 'Gerli, Provincia de Buenos Aires', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/57800.png'),
(57801, 'Always Ready', 'Club Always Ready', 'La Paz', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/57801.png'),
(58165, 'Atlanta United', 'Atlanta United FC', 'Atlanta, Georgia', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/58165.png'),
(58269, 'Guaireña', 'Guaireña Fútbol Club', 'Villarrica', 600, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/58269.png'),
(60341, 'UD Ibiza', 'UD Ibiza', 'Ibiza Town', 724, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g39898_120x120.png'),
(61030, 'Volos NFC', 'Volos New Football Club', 'Volos', 300, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/61030.png'),
(61967, 'Carlos Stein', 'FC Carlos Stein', 'Chiclayo', 604, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/61967.png'),
(62148, 'Los Angeles FC', 'Los Angeles FC', '', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/62148.png'),
(63704, 'Orense', 'Orense SC', '', 218, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/63704.png'),
(66104, 'Atlético Palmaflor', 'Club Atlético Palmaflor', '', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66104.png'),
(66193, 'Inter Miami', 'Club Internacional de Fútbol Miami', 'Miami', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66193.png'),
(66663, 'Gimnasia La Plata', 'Gimnasia y Esgrima la Plata', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66663.png'),
(66664, 'Racing Club', 'Racing Club de Avellaneda', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66664.png'),
(66665, 'Rosario Central', 'CA Rosario Central', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66665.png'),
(66666, 'Lanús', 'CA Lanús', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66666.png'),
(66667, 'SAT', 'Social Atletico Television', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66667.png'),
(66668, 'Defensores de Belgrano', 'CA Defensores de Belgrano', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66668.png'),
(66847, 'Mazatlán', 'Mazatlán FC', '', 484, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/66847.png'),
(66957, 'Cancún', 'Cancún FC', '', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g-12734_120x120.png'),
(66958, 'Pumas Tabasco', 'Soccer Pumas de Tabasco', '', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g-12735_120x120.png'),
(66959, 'Tapatío', 'CD Tapatío', '', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g-12736_120x120.png'),
(67860, 'Austin FC', 'Austin FC', '', 840, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/67860.png'),
(68039, 'Independiente Petrolero', 'Club Independiente Petrolero', 'Sucre', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/68039.png'),
(68040, 'Real Tomayapo', 'CD Real Tomayapo', 'Tarija', 68, 'club', 'male', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/68040.png'),
(68136, 'Deportivo Español', 'Club Deportivo Español', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/68136.png'),
(68137, 'Comunicaciones', 'Club Comunicaciones de Buenos Aires', '', 32, 'club', 'female', 'https://bi-sports-teams.s3.sa-east-1.amazonaws.com/68137.png'),
(68502, 'Raya2', 'Raya2 Expansion', 'Monterrey', 484, 'club', 'male', 'https://cdn5.wyscout.com/photos/team/public/g-14230_120x120.png');
